const products: Product[] = [
	{
		image: "/chcotorta.jpeg",
		name: "choco-deli",
		price: 400,
		tags: ["favorito de los clientes", "más vendidos"],
		description: null,
		types: null,
		discount: null,
		images: ["/torta.jpeg", "/chocooreo.jpeg", "/sweet.jpeg"],
		id: 1,
		userId: 1,
	},
	{
		image: "/torta.jpeg",
		name: "torta 1kg",
		price: 2400,
		tags: null,
		description: "Se puede pedor de mayor tamaño",
		types: null,
		discount: 20,
		images: ["/chcotorta.jpeg", "/torta.jpeg", "/chocooreo.jpeg"],
		id: 2,
		userId: 1,
	},
	{
		image: "/chocooreo.jpeg",
		name: "oreo-deli",
		price: 400,
		tags: ["destacado"],
		description: null,
		types: ["chico", "grande"],
		discount: null,
		images: null,
		id: 3,
		userId: 1,
	},
	{
		image: "/sweet.jpeg",
		name: "vaso grande",
		price: 900,
		tags: ["nuevo"],
		description: "vaso con golosinas para regalo",
		types: null,
		discount: null,
		images: null,
		id: 4,
		userId: 1,
	},
	{
		image: "/sweet.jpeg",
		name: "vaso chico",
		price: 500,
		tags: ["nuevo"],
		description: "vaso con golosinas para regalo",
		types: null,
		discount: null,
		images: null,
		id: 5,
		userId: 1,
	},
	{
		image: "",
		name: "test",
		price: null,
		tags: null,
		description: "Esta es la descripcion",
		types: null,
		discount: null,
		images: null,
		id: 6,
		userId: 1,
	},
];

export default products;
